FairRootGroup/DDS

dds-protocol-lib/src/BaseSMChannelImpl.h
Due to a wrong order of the parameters in the constructor it was not possible to send messages more than 100 bytes in shared memory channel.
=> Fix bug in shared memory channel

dds-commander/src/ConnectionManager.cpp, dds-protocol-lib/src/UpdateTopologyCmd.cpp, dds-protocol-lib/src/UpdateTopologyCmd.h, dds-topology/src/ActivateChannel.cpp, dds-topology/src/Options.h
The disable-validation check was always triggered preventing the user
from using e.g. --stop. This patch also fixes a typo in the variable
names in dds-topology, dds-protocol-lib, and dds-commander.
---
Note: I created this patch against DDS 1.6. In `master` the problem was already fixed. But I still propose my patch because it fixes a typo and drops `vm.count("disable-validation")` which always returns `1`.
=> dds-topology: fix --disable-validation option

dds-protocol-lib/src/BaseSMChannelImpl.h, dds-session/src/Start.cpp
`warning: control reaches end of non-void function`
reported by gcc 8.1.1
Full log:
```
╭─dklein@gamma ~/projects/DDS/build  ‹master*› 
╰─➤  cmake -GNinja -DCMAKE_PREFIX_PATH=/home/dklein/fairsoft_may18 -DCMAKE_INSTALL_PREFIX=./install ..
-- The C compiler identification is GNU 8.1.1
-- The CXX compiler identification is GNU 8.1.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- …
```
=> Fix -Wreturn-type and small bug in dds-session

dds-tutorials/dds-tutorial1/CMakeLists.txt
The error I got was:
```
In file included from /home/dklein/fairsoft_may18/include/boost/function/detail/maybe_include.hpp:36,
from /home/dklein/fairsoft_may18/include/boost/function/detail/function_iterate.hpp:14,
from /home/dklein/fairsoft_may18/include/boost/preprocessor/iteration/detail/iter/forward1.hpp:62,
from /home/dklein/fairsoft_may18/include/boost/function.hpp:70,
from /home/dklein/fairsoft_may18/include/boost/signals2/signal.hpp:18,
from /home/dklein/fairsoft_may18/include/dds_intercom_error_codes.h:10,
from /home/dklein/fairsoft_may18/include/dds_intercom.h:10,
from /home/dklein/projects/DDS/dds-tutorials/dds-tutorial1/task-type-two.cpp:2:
/home/dklein/fairsoft_may18/include/boost/function/function_template.hpp: In instantiation of ‘static void …
```
=> Fix order of include directories

dds-session/src/main.cpp
Just noticed this by coincidence, not really important.
=> dds-session list: Retrieve default session only once

CMakeLists.txt
This is required because the new config mechanism of 1.70.0
seems to prefer static libraries by default if BUILD_SHARED_LIBS
is not explicitly set, resulting in a bunch of undefined symbols
coming from the fact you use:
explicitly in DDS/MiscCommon/Logger.h . Not sure if this is the most
elegant solution, but it pragmatically works in my setup.
=> Fix issue when boost 1.70.0 has both static and shared libs

plugins/dds-submit-ssh/src/dds-submit-ssh-worker, plugins/dds-submit-ssh/src/main.cpp, plugins/dds-submit-ssh/src/worker.cpp
The first commit fixes a bug in the getopts config within the `dds-submit-ssh-worker` script which had the effect that, if a user ssh option was set, the `-n` argument passed after was not properly parsed (at least on Fedora 30 the script was always spawning exactly 1 agent in the presence of a `-o` option).
The second commit is obviously very optional, but I found it very useful. (If you don't like it, you can push to my branch and remove it or I can remove it)
=> Fix dds-submit user ssh options

dds-topology-lib/src/Topology.cpp
I missed a function definition in #232, my bad :-( This fixes it.
```
/usr/bin/ld: fairmq/sdk/libFairMQ_SDK.so.1.4.5-87-g7d1ee82-dirty: undefined reference to `dds::topology_api::CTopology::getName[abi:cxx11]() const'
```
=> dds-topology-lib: Add missing member function definition

dds-intercom-lib/src/DDSIntercomGuard.cpp
It makes me also think, if we need threadsafety in this class? E.g. if the user sends a custom command reply directly in a callback which is executed on the thread pool?
=> dds-intercom-lib: Fix thread leak

ReleaseNotes.md, dds-commander/src/ConnectionManager.cpp, dds-commander/src/ConnectionManager.h, dds-info/src/Options.h, dds-info/src/main.cpp, dds-tools-lib/src/ToolsProtocol.cpp, dds-tools-lib/src/ToolsProtocol.h, dds-tools-lib/tests/Test.cpp, dds-tools-lib/tests/test_protocol_1.json
- Move agent counter request data from commander info to agent info request;
- Refactor sending of custom cmds and done responses for commander;
- Update tolls API unit tests of request/response data.
=> Add --wait-for-executing-agents option

dds-tools-lib/src/ToolsProtocol.h
With current DDS master I get:
```In file included from ~/dev/FairSoft/basics/DDS/dds-tools-lib/src/ToolsProtocol.cpp:6:
~/dev/FairSoft/basics/DDS/dds-tools-lib/src/ToolsProtocol.h:164:18: error: ‘chrono’ in namespace ‘std’ does not name a type
std::chrono::milliseconds m_startUpTime = std::chrono::milliseconds(0); ///< Agent's startup time```
=> Add missing include

CMakeLists.txt, ReleaseNotes.md, dds-agent/src/CommanderChannel.cpp, dds-commander/src/ConnectionManager.cpp, dds-protocol-lib/src/BaseChannelImpl.h, dds-protocol-lib/src/BaseSMChannelImpl.h
- Use BOOST BOOST_INTERPROCESS_ENABLE_TIMEOUT_WHEN_LOCKING flag. It forces the boost::interprocess to use timed mutexes instead of a simple ones. This fixes the issue if process is killed or crased and leaves opened and locked interprocess mutex.
- Fix topology update logic: first stop the tasks and than update the topology on agents.
- SM channel: seperate mutexes for input and output containers of message_queue.
- Fix agent replies during topology update
=> Fixed topology update

MiscCommon/Process.h, MiscCommon/tests/Test_Process.cpp, MiscCommon/tests/Test_SysHelper.cpp
- Do not create process group in execute(). The reason is that dds-daemonize uses ::setsid.
- Create unit test for execute() and dds-daemonize
=> Fix execute()

dds-submit/src/Options.h
Some older compilers (gcc 4.9-5.1) do not like brace initialization.
This fixes the compile for us.
Can you please check, if this change is okay for you?
Thanks go to @dennisklein for helping.
=> Fix compile on older compilers

ReleaseNotes.md, dds-topology-lib/src/TopoCore.cpp, dds-topology-lib/src/TopoCore.h, dds-topology-lib/src/Topology.cpp, dds-topology-lib/src/Topology.h, dds-topology-lib/tests/Test.cpp
New methods take as input either ID or a runtime path.
=> dds-topology: new getRuntimeTask and getRuntimeCollection methods

MiscCommon/tests/CMakeLists.txt, MiscCommon/tests/Test_SysHelper.cpp
Unique path is required to be able to start multiple test runs in parallel
=> Use temp path for a file

ReleaseNotes.md, dds-agent/src/CommanderChannel.cpp, dds-agent/src/CommanderChannel.h, dds-topology-lib/src/TopoCore.h
- in some edge cases a topology update, performed during an intensive key-value exchange, can lead to a segmentaion fault.
=> Fixed a case when topology object goes out of scope

dds-session/src/main.cpp, dds-tools-lib/tests/TestSession.cpp
- if some of the action failed after DDS commander was successfully started, do not exit with error.
- do not compare default session ID with the newly created session ID. It can fail in case of a parallel test execution.
=> dds-session: fix start behaviour

dds-agent/src/CommanderChannel.cpp, dds-tools-lib/tests/TestSession.cpp
- Disable queque drain during task assignment instead of task activation.
- Enable checks in unit tests that task finisherd successfully.
=> Fix queue drain for intercom channel

dds-tools-lib/tests/TestSession.cpp
- We need a multiple session support for our unit tests. So use a workaround until CUserDefaults::getAgentLogStorageDir() is fixed.
=> Workaround for CUserDefaults::getAgentLogStorageDir()

codemeta.json
codemeta.json is becoming a standard format for describing software. Let's start to add it.
This is also starting to get relevant in the context of ESCAPE.
I created the current codemeta.json to match the entry on zenodo as closely as possible. That means, that any issues with the zenodo entry are also issues with the codemeta data.
Notes:
* zenodo lists the license as CC-BY-4.0 (also reflected into the codemeta.json file)
github lists it as LGPL-3.0 (either "only" or "and-later", not checked that details)
Helpful:
* There is a codemeta generator/viewer: https://codemeta.github.io/codemeta-generator/
You can even paste the suggested codemeta.json there and view it.
=> Start to add codemeta.json

ReleaseNotes.md, bin/dds-prep-worker, dds-agent/src/AgentConnectionManager.cpp, dds-agent/src/CommanderChannel.cpp, dds-agent/src/CommanderChannel.h, dds-agent/src/Options.h, dds-commander/src/ConnectionManager.cpp, dds-commander/src/ConnectionManager.h, dds-commander/src/Scheduler.cpp, dds-commander/src/Scheduler.h, dds-commander/tests/TestScheduler.cpp, dds-commander/tests/topology_scheduler_test_2.xml, dds-intercom-lib/src/Intercom.h, dds-intercom-lib/src/dds_rms_plugin_protocol.cpp, dds-protocol-lib/src/HostInfoCmd.cpp, dds-protocol-lib/src/HostInfoCmd.h, dds-protocol-lib/tests/Test_ProtocolMessage.cpp, dds-submit/src/Options.h, dds-submit/src/main.cpp, dds-tools-lib/src/ToolsProtocol.cpp, dds-tools-lib/src/ToolsProtocol.h, dds-topology-lib/src/TopoRequirement.h, dds-topology-lib/src/TopoUtils.cpp, etc/DDSWorker.sh.in, res/topology.xsd
dds-submit: Added: Users can specify a GroupName tag for each submission. This tag will be assigned to agents and can be used as a requirement in topologies. (GH-407)
dds-topology: Added: A new groupName requirement. It can be used on task and collection. (GH-407)
=> GH-407: Add agent groups support

CMakeLists.txt
Patch by @dennisklein
See: https://github.com/FairRootGroup/FairSoft/commit/3f1e93456e660a68d7393adbdbe2e9069f570a41
=> Allow setting DDS_LD_LIBRARY_PATH as CMake var

ReleaseNotes.md, dds-topology-lib/src/TopoAsset.cpp, dds-topology-lib/src/TopoBase.cpp, dds-topology-lib/src/TopoBase.h, dds-topology-lib/src/TopoContainer.cpp, dds-topology-lib/src/TopoContainer.h, dds-topology-lib/src/TopoTask.cpp
dds-topology: Fix activating topology takes too long when task assets are used. (GH-454)
=> GH-454: Fix activating topology takes long with assets (GH-454)

dds-agent/src/CommanderChannel.cpp
Not sure if this is fully correct and compatible, but if I understand correctly the boost ifstream/ofstream is deprecated and one should use the std variants instead, and this one compiles for me with boost 1.79.
=> Replace deprecated boost:filesystem::ifstream/ofstream with std:: version

ReleaseNotes.md, dds-agent/src/CommanderChannel.cpp
Fixed: a regression bug causing topology update to fail on the hash validation. (GH-480)
=> GH-480: Fix topology update

dds-protocol-lib/src/BaseEventHandlersImpl.h
Fixes #373, which continuously leads to test failures in ODC: https://cdash.gsi.de/testDetails.php?test=21606495&build=473806
The issue is that SHandlerHlpBaseFunc containing `T m_signal` is stored in a `std::map<Event_t, std::unique_ptr<SHandlerHlpFunc>> signalsContainer_t;`, with pointers to the base type. And since the base type has no virtual destructor, it then does not take care of deleting child's objects properly. 
I tested this change locally and it fixes the new-delete-type-mismatch.
=> Fix new-delete-type-mismatch in BaseEventHandlersImpl.h

README.md, dds-agent-cmd/README.md, dds-info/README.md, dds-session/README.md, dds-submit/README.md, dds-topology/README.md, dds-tutorials/dds-tutorial3/run_tutorial3.sh, dds-user-defaults/README.md, docs/3rd-party.md, docs/download.md, docs/how-to-start.md, docs/install.md, docs/quick-start.md, docs/requirements.md, docs/tutorials.md, docs/user-defaults-configuration.md, plugins/dds-submit-slurm/README.md
- Restructure main README with clearer feature descriptions and better navigation
- Add detailed examples and usage patterns to CLI tool documentation (dds-session, dds-info, dds-topology, etc.)
- Create comprehensive user defaults configuration reference with all available options
- Update tutorials with better automation examples and clearer instructions
- Improve documentation formatting and add more practical examples throughout
- Update links to point to GitHub releases instead of legacy download pages
- Fix minor typos and improve consistency across documentation files
This update makes the documentation more user-friendly and provides better
guidance for both new users and advanced configurations.
=> docs: improve README structure and add comprehensive CLI documentation
